language: bash
os:
  - osx
env:
  # - FLUTTER_CHANNEL="stable"
  - FLUTTER_CHANNEL="master"
sudo: false
before_install:
    - chmod +x scripts/flutter_test.sh
before_script:
    - git clone https://github.com/flutter/flutter.git -b beta
    - ./flutter/bin/flutter doctor
script:
  - set -e # abort CI if an error happens
  - ./flutter/bin/flutter test

  # export coverage
  - if [ $FLUTTER_CHANNEL = "master" ]; then
    bash <(curl -s https://codecov.io/bash);
    fi
matrix:
  fast_finish: true
  # allow_failures:
  # - env: FLUTTER_CHANNEL="master"
cache:
  directories:
    - $HOME/.pub-cache

